/* Generated by tools/build_plan.py from source/INS_Inspection_Flow.xlsx - do not edit by hand */
window.PLAN = {
 "company": "DATRE CORPORATION LIMITED",
 "title": "Casting Process Flow – Inspection Plan",
 "stages": [
  {
   "no": 1,
   "name": "Pattern & Core Box Making",
   "scope": "job",
   "groups": [
    {
     "name": null,
     "steps": [
      {
       "id": "1.1",
       "name": "Making of Pattern Layout",
       "checks": [
        {
         "id": "1.1.1",
         "step": "1.1",
         "sample": "1",
         "param": "Dimension",
         "method": "Contraction scale, angle protector, calipers",
         "criteria": "As per drawing, measured by contraction scale",
         "action": "Layout rectification",
         "actions": [
          "Layout rectification"
         ],
         "tbc": false,
         "kind": "dim"
        }
       ],
       "optional": false,
       "sampled": false
      },
      {
       "id": "1.2",
       "name": "Making of Templates",
       "checks": [
        {
         "id": "1.2.1",
         "step": "1.2",
         "sample": "1",
         "param": "Matching with layout",
         "method": "Pattern layout",
         "criteria": "Absolutely matched with layout",
         "action": "Rectification or remaking",
         "actions": [
          "Rectification or remaking"
         ],
         "tbc": false,
         "kind": "yn"
        }
       ],
       "optional": false,
       "sampled": false
      },
      {
       "id": "1.3",
       "name": "Manufacturing of Pattern & Core Box",
       "checks": [
        {
         "id": "1.3.1",
         "step": "1.3",
         "sample": "1",
         "param": "Dimension",
         "method": "Pattern layout, templates, angle protector, contraction scale, calipers",
         "criteria": "As per drawing, measured by contraction scale",
         "action": "Rectification",
         "actions": [
          "Rectification"
         ],
         "tbc": false,
         "kind": "dim"
        },
        {
         "id": "1.3.2",
         "step": "1.3",
         "sample": "1",
         "param": "Surface finish, coating, visual defects",
         "method": "Visual check",
         "criteria": "Internal standard",
         "action": "Rectification",
         "actions": [
          "Rectification"
         ],
         "tbc": false,
         "kind": "yn"
        }
       ],
       "optional": false,
       "sampled": false
      },
      {
       "id": "1.4",
       "name": "Match Plate Fitting & Methoding",
       "checks": [
        {
         "id": "1.4.1",
         "step": "1.4",
         "sample": "1",
         "param": "Dimension",
         "method": "Scale, tape, vernier scale, calipers",
         "criteria": "Method drawing",
         "action": "Rectification",
         "actions": [
          "Rectification"
         ],
         "tbc": false,
         "kind": "dim"
        }
       ],
       "optional": false,
       "sampled": false
      }
     ]
    }
   ],
   "optional": false
  },
  {
   "no": 2,
   "name": "Sand Preparation, Calibration & Mix Testing",
   "scope": "log",
   "groups": [
    {
     "name": "Sand quality",
     "steps": [
      {
       "id": "2.1",
       "name": "New Sand (P1)",
       "checks": [
        {
         "id": "2.1.1",
         "step": "2.1",
         "sample": "Per incoming QAP",
         "param": "Incoming sand verified",
         "method": "Doc No. DCL/QAP/ICI",
         "criteria": "All details as per Quality Assurance Plan for Critical Incoming Material, Doc No. DCL/QAP/ICI",
         "action": "Reject lot / return to supplier",
         "actions": [
          "Reject lot / return to supplier"
         ],
         "tbc": false,
         "kind": "yn",
         "freq": "shift"
        }
       ],
       "optional": false,
       "sampled": false
      },
      {
       "id": "2.2",
       "name": "Reclaimed Sand (P2)",
       "checks": [
        {
         "id": "2.2.1",
         "step": "2.2",
         "sample": "100 gms min at start of shift",
         "param": "Fines %",
         "method": "Sieve shaker & weighing balance",
         "criteria": "5% Max",
         "action": "Increase new sand addition / Disposal of sand",
         "actions": [
          "Increase new sand addition",
          "Disposal of sand"
         ],
         "tbc": false,
         "kind": "max",
         "max": 5.0,
         "unit": "%",
         "freq": "shift"
        },
        {
         "id": "2.2.2",
         "step": "2.2",
         "sample": "100 gms min at start of shift",
         "param": "Moisture %",
         "method": "Muffle furnace & weighing balance",
         "criteria": "1% Max",
         "action": "Increase new sand addition / Disposal of sand",
         "actions": [
          "Increase new sand addition",
          "Disposal of sand"
         ],
         "tbc": false,
         "kind": "max",
         "max": 1.0,
         "unit": "%",
         "freq": "shift"
        },
        {
         "id": "2.2.3",
         "step": "2.2",
         "sample": "100 gms once in a week",
         "param": "LOI",
         "method": "Muffle furnace & weighing balance",
         "criteria": "3.5 Max",
         "action": "Increase new sand addition / Disposal of sand",
         "actions": [
          "Increase new sand addition",
          "Disposal of sand"
         ],
         "tbc": false,
         "kind": "max",
         "max": 3.5,
         "unit": "%",
         "freq": "weekly"
        }
       ],
       "optional": false,
       "sampled": false
      },
      {
       "id": "2.3",
       "name": "Mixed Sand (P3)",
       "checks": [
        {
         "id": "2.3.1",
         "step": "2.3",
         "sample": "100 gms min at start of shift",
         "param": "Fines %",
         "method": "Sieve shaker & weighing balance",
         "criteria": "5% Max",
         "action": "Increase new sand addition / Disposal of sand",
         "actions": [
          "Increase new sand addition",
          "Disposal of sand"
         ],
         "tbc": false,
         "kind": "max",
         "max": 5.0,
         "unit": "%",
         "freq": "shift"
        },
        {
         "id": "2.3.2",
         "step": "2.3",
         "sample": "100 gms min at start of shift",
         "param": "Moisture %",
         "method": "Muffle furnace & weighing balance",
         "criteria": "1% Max",
         "action": "Increase new sand addition / Disposal of sand",
         "actions": [
          "Increase new sand addition",
          "Disposal of sand"
         ],
         "tbc": false,
         "kind": "max",
         "max": 1.0,
         "unit": "%",
         "freq": "shift"
        },
        {
         "id": "2.3.3",
         "step": "2.3",
         "sample": "100 gms once in a week",
         "param": "LOI",
         "method": "Muffle furnace & weighing balance",
         "criteria": "3 Max",
         "action": "Increase new sand addition / Disposal of sand",
         "actions": [
          "Increase new sand addition",
          "Disposal of sand"
         ],
         "tbc": false,
         "kind": "max",
         "max": 3.0,
         "unit": "%",
         "freq": "weekly"
        }
       ],
       "optional": false,
       "sampled": false
      }
     ]
    },
    {
     "name": "Machine calibration",
     "steps": [
      {
       "id": "2.4",
       "name": "Resin Calibration",
       "checks": [
        {
         "id": "2.4.1",
         "step": "2.4",
         "sample": "Once a day min",
         "param": "Volume in 15 sec",
         "method": "Measuring cylinder 1000 ml",
         "criteria": "1.8–2 % of sand wt",
         "action": "Re-adjust",
         "actions": [
          "Re-adjust"
         ],
         "tbc": false,
         "kind": "range",
         "min": 1.8,
         "max": 2.0,
         "unit": "% of sand wt",
         "freq": "daily"
        }
       ],
       "optional": false,
       "sampled": false
      },
      {
       "id": "2.5",
       "name": "Catalyst Calibration",
       "checks": [
        {
         "id": "2.5.1",
         "step": "2.5",
         "sample": "Once a day min",
         "param": "Volume in 15 sec",
         "method": "Measuring cylinder 500 ml",
         "criteria": "18–21 % of resin wt",
         "action": "Re-adjust",
         "actions": [
          "Re-adjust"
         ],
         "tbc": false,
         "kind": "range",
         "min": 18.0,
         "max": 21.0,
         "unit": "% of resin wt",
         "freq": "daily"
        }
       ],
       "optional": false,
       "sampled": false
      },
      {
       "id": "2.6",
       "name": "P1 Sand Calibration",
       "checks": [
        {
         "id": "2.6.1",
         "step": "2.6",
         "sample": "Once in three months min",
         "param": "Weight in 15 sec",
         "method": "Weighing scale",
         "criteria": "60 to 70 kg / 15 sec",
         "action": "Adjust sand gate opening",
         "actions": [
          "Adjust sand gate opening"
         ],
         "tbc": false,
         "kind": "range",
         "min": 60.0,
         "max": 70.0,
         "unit": "kg / 15 sec",
         "freq": "quarterly"
        }
       ],
       "optional": false,
       "sampled": false
      },
      {
       "id": "2.7",
       "name": "P2 Sand Calibration",
       "checks": [
        {
         "id": "2.7.1",
         "step": "2.7",
         "sample": "Once in three months min",
         "param": "Weight in 15 sec",
         "method": "Weighing scale",
         "criteria": "60 to 70 kg / 15 sec",
         "action": "Adjust sand gate opening",
         "actions": [
          "Adjust sand gate opening"
         ],
         "tbc": false,
         "kind": "range",
         "min": 60.0,
         "max": 70.0,
         "unit": "kg / 15 sec",
         "freq": "quarterly"
        }
       ],
       "optional": false,
       "sampled": false
      },
      {
       "id": "2.8",
       "name": "P3 Sand Calibration",
       "checks": [
        {
         "id": "2.8.1",
         "step": "2.8",
         "sample": "Once in three months min",
         "param": "Weight in 15 sec",
         "method": "Weighing scale",
         "criteria": "20–25 kg of total 70–75 kg / 15 sec",
         "action": "Adjust sand gate opening",
         "actions": [
          "Adjust sand gate opening"
         ],
         "tbc": false,
         "kind": "range",
         "min": 20.0,
         "max": 25.0,
         "unit": "kg / 15 sec",
         "freq": "quarterly"
        }
       ],
       "optional": false,
       "sampled": false
      },
      {
       "id": "2.9",
       "name": "P3 Reclaim Sand Calibration",
       "checks": [
        {
         "id": "2.9.1",
         "step": "2.9",
         "sample": "Once in three months min",
         "param": "Weight in 15 sec",
         "method": "Weighing scale",
         "criteria": "50–55 kg of total 70–75 kg / 15 sec",
         "action": "Adjust sand gate opening",
         "actions": [
          "Adjust sand gate opening"
         ],
         "tbc": false,
         "kind": "range",
         "min": 50.0,
         "max": 55.0,
         "unit": "kg / 15 sec",
         "freq": "quarterly"
        }
       ],
       "optional": false,
       "sampled": false
      }
     ]
    },
    {
     "name": "Sand mix testing",
     "steps": [
      {
       "id": "2.10",
       "name": "Sand Mix P1",
       "checks": [
        {
         "id": "2.10.1",
         "step": "2.10",
         "sample": "Min once every shift",
         "param": "Compressive strength",
         "method": "Universal strength testing machine",
         "criteria": "6 kg/cm² min after keeping 10 min at 150 °C",
         "action": "Adjust resin and catalyst %",
         "actions": [
          "Adjust resin and catalyst %"
         ],
         "tbc": false,
         "kind": "min",
         "min": 6.0,
         "unit": "kg/cm²",
         "freq": "shift"
        },
        {
         "id": "2.10.2",
         "step": "2.10",
         "sample": "Min once every shift",
         "param": "Transverse strength",
         "method": "Universal strength testing machine",
         "criteria": "3 kg/cm² min after keeping 10 min at 150 °C",
         "action": "Adjust resin and catalyst %",
         "actions": [
          "Adjust resin and catalyst %"
         ],
         "tbc": false,
         "kind": "min",
         "min": 3.0,
         "unit": "kg/cm²",
         "freq": "shift"
        },
        {
         "id": "2.10.3",
         "step": "2.10",
         "sample": "Min once every shift",
         "param": "Impact penetration",
         "method": "Impact penetration testing machine",
         "criteria": "Mix 2.5 mm measured after 1 hr of stripping",
         "action": "Adjust resin and catalyst %",
         "actions": [
          "Adjust resin and catalyst %"
         ],
         "tbc": false,
         "kind": "max",
         "max": 2.5,
         "unit": "mm",
         "assumed": true,
         "freq": "shift"
        }
       ],
       "optional": false,
       "sampled": false
      },
      {
       "id": "2.11",
       "name": "Sand Mix P2",
       "checks": [
        {
         "id": "2.11.1",
         "step": "2.11",
         "sample": "Min once every shift",
         "param": "Compressive strength",
         "method": "Universal strength testing machine",
         "criteria": "6 kg/cm² min after keeping 10 min at 150 °C",
         "action": "Adjust resin and catalyst %",
         "actions": [
          "Adjust resin and catalyst %"
         ],
         "tbc": false,
         "kind": "min",
         "min": 6.0,
         "unit": "kg/cm²",
         "freq": "shift"
        },
        {
         "id": "2.11.2",
         "step": "2.11",
         "sample": "Min once every shift",
         "param": "Transverse strength",
         "method": "Universal strength testing machine",
         "criteria": "3 kg/cm² min after keeping 10 min at 150 °C",
         "action": "Adjust resin and catalyst %",
         "actions": [
          "Adjust resin and catalyst %"
         ],
         "tbc": false,
         "kind": "min",
         "min": 3.0,
         "unit": "kg/cm²",
         "freq": "shift"
        },
        {
         "id": "2.11.3",
         "step": "2.11",
         "sample": "Min once every shift",
         "param": "Gas content",
         "method": "Core gas determinator",
         "criteria": "10 cc/gm of sand Max",
         "action": "Increase new sand addition / Disposal of sand",
         "actions": [
          "Increase new sand addition",
          "Disposal of sand"
         ],
         "tbc": false,
         "kind": "max",
         "max": 10.0,
         "unit": "cc/gm",
         "freq": "shift"
        },
        {
         "id": "2.11.4",
         "step": "2.11",
         "sample": "Min once every shift",
         "param": "Impact penetration",
         "method": "Impact penetration testing machine",
         "criteria": "Mix 2.6 mm measured after 1 hr of stripping",
         "action": "Adjust resin and catalyst %",
         "actions": [
          "Adjust resin and catalyst %"
         ],
         "tbc": false,
         "kind": "max",
         "max": 2.6,
         "unit": "mm",
         "assumed": true,
         "freq": "shift"
        }
       ],
       "optional": false,
       "sampled": false
      },
      {
       "id": "2.12",
       "name": "Sand Mix P3",
       "checks": [
        {
         "id": "2.12.1",
         "step": "2.12",
         "sample": "Min once every shift",
         "param": "Compressive strength",
         "method": "Universal strength testing machine",
         "criteria": "6 kg/cm² min after keeping 10 min at 150 °C",
         "action": "Adjust resin and catalyst %",
         "actions": [
          "Adjust resin and catalyst %"
         ],
         "tbc": false,
         "kind": "min",
         "min": 6.0,
         "unit": "kg/cm²",
         "freq": "shift"
        },
        {
         "id": "2.12.2",
         "step": "2.12",
         "sample": "Min once every shift",
         "param": "Transverse strength",
         "method": "Universal strength testing machine",
         "criteria": "3 kg/cm² min after keeping 10 min at 150 °C",
         "action": "Adjust resin and catalyst %",
         "actions": [
          "Adjust resin and catalyst %"
         ],
         "tbc": false,
         "kind": "min",
         "min": 3.0,
         "unit": "kg/cm²",
         "freq": "shift"
        },
        {
         "id": "2.12.3",
         "step": "2.12",
         "sample": "Min once every shift",
         "param": "Gas content",
         "method": "Core gas determinator",
         "criteria": "10 cc/gm of sand Max",
         "action": "Increase new sand addition / Disposal of sand",
         "actions": [
          "Increase new sand addition",
          "Disposal of sand"
         ],
         "tbc": false,
         "kind": "max",
         "max": 10.0,
         "unit": "cc/gm",
         "freq": "shift"
        },
        {
         "id": "2.12.4",
         "step": "2.12",
         "sample": "Min once every shift",
         "param": "Impact penetration",
         "method": "Impact penetration testing machine",
         "criteria": "Mix 2.7 mm measured after 1 hr of stripping",
         "action": "Adjust resin and catalyst %",
         "actions": [
          "Adjust resin and catalyst %"
         ],
         "tbc": false,
         "kind": "max",
         "max": 2.7,
         "unit": "mm",
         "assumed": true,
         "freq": "shift"
        }
       ],
       "optional": false,
       "sampled": false
      }
     ]
    }
   ],
   "optional": false
  },
  {
   "no": 3,
   "name": "Mould & Core Preparation",
   "scope": "casting",
   "groups": [
    {
     "name": null,
     "steps": [
      {
       "id": "3.1",
       "name": "Mould Coating",
       "checks": [
        {
         "id": "3.1.1",
         "step": "3.1",
         "sample": "In every batch",
         "param": "Viscosity",
         "method": "Baume meter",
         "criteria": "55–65 Baume",
         "action": "Re-mix",
         "actions": [
          "Re-mix"
         ],
         "tbc": false,
         "kind": "range",
         "min": 55.0,
         "max": 65.0,
         "unit": "Baumé"
        },
        {
         "id": "3.1.2",
         "step": "3.1",
         "sample": "1",
         "param": "Area covered, surface finish & peel off",
         "method": "Visual",
         "criteria": "Desired surface covered, smooth surface finish, no peel off after heating",
         "action": "Repainting",
         "actions": [
          "Repainting"
         ],
         "tbc": false,
         "kind": "yn"
        }
       ],
       "optional": false,
       "sampled": false
      },
      {
       "id": "3.2",
       "name": "Mould & Core Hardness",
       "checks": [
        {
         "id": "3.2.1",
         "step": "3.2",
         "sample": "10% min",
         "param": "Scratch hardness",
         "method": "Scratch hardness tester",
         "criteria": "Hardness 50 min",
         "action": "Destroyed",
         "actions": [
          "Destroyed"
         ],
         "tbc": false,
         "kind": "min",
         "min": 50.0,
         "unit": "scratch hardness"
        }
       ],
       "optional": false,
       "sampled": true
      },
      {
       "id": "3.3",
       "name": "Mould & Core Setting",
       "checks": [
        {
         "id": "3.3.1",
         "step": "3.3",
         "sample": "1",
         "param": "Visual – only good mould/core to be used",
         "method": "Visual",
         "criteria": "Mould & core properly cleaned; no damage / loose particles",
         "action": "Repaired",
         "actions": [
          "Repaired"
         ],
         "tbc": false,
         "kind": "yn"
        }
       ],
       "optional": false,
       "sampled": false
      },
      {
       "id": "3.4",
       "name": "Closing",
       "checks": [
        {
         "id": "3.4.1",
         "step": "3.4",
         "sample": "1",
         "param": "Closing condition",
         "method": "Visual",
         "criteria": "No loose sand, no gap, all vents clear, closing pin fitted",
         "action": "Re-close after repair / destroyed",
         "actions": [
          "Re-close after repair",
          "Destroyed"
         ],
         "tbc": false,
         "kind": "yn"
        }
       ],
       "optional": false,
       "sampled": false
      }
     ]
    }
   ],
   "optional": false
  },
  {
   "no": 4,
   "name": "Melting & Pouring",
   "scope": "heat",
   "groups": [
    {
     "name": null,
     "steps": [
      {
       "id": "4.1",
       "name": "Melting Process",
       "checks": [
        {
         "id": "4.1.1",
         "step": "4.1",
         "sample": "Each bath",
         "param": "All elements as per specification",
         "method": "Online spectrometer",
         "criteria": "As per drawing / standard specification",
         "action": "Addition of ferro alloys / Pig the melt",
         "actions": [
          "Addition of ferro alloys",
          "Pig the melt"
         ],
         "tbc": false,
         "kind": "chem"
        }
       ],
       "optional": false,
       "sampled": false
      },
      {
       "id": "4.2",
       "name": "Final Chemical Composition",
       "checks": [
        {
         "id": "4.2.1",
         "step": "4.2",
         "sample": "Each heat",
         "param": "All elements as per specification",
         "method": "Online spectrometer",
         "criteria": "As per drawing / standard specification",
         "action": "Reject all castings poured",
         "actions": [
          "Reject all castings poured"
         ],
         "tbc": false,
         "kind": "chem"
        }
       ],
       "optional": false,
       "sampled": false
      },
      {
       "id": "4.3",
       "name": "Tapping",
       "checks": [
        {
         "id": "4.3.1",
         "step": "4.3",
         "sample": "Before tapping",
         "param": "Tapping temperature",
         "method": "Immersion pyrometer",
         "criteria": "As per method plan Doc No. DCL/MTD/01",
         "action": "Adjust temperature",
         "actions": [
          "Adjust temperature"
         ],
         "tbc": false,
         "kind": "spec",
         "unit": "°C"
        }
       ],
       "optional": false,
       "sampled": false
      },
      {
       "id": "4.4",
       "name": "Pouring",
       "checks": [
        {
         "id": "4.4.1",
         "step": "4.4",
         "sample": "From ladle during first mould pouring of each heat",
         "param": "Pouring temperature",
         "method": "Immersion pyrometer",
         "criteria": "As per method plan Doc No. DCL/MTD/01",
         "action": "Wait (if high) / Back to furnace (if low)",
         "actions": [
          "Wait (if high)",
          "Back to furnace (if low)"
         ],
         "tbc": false,
         "kind": "spec",
         "unit": "°C"
        }
       ],
       "optional": false,
       "sampled": false
      }
     ]
    }
   ],
   "optional": false
  },
  {
   "no": 5,
   "name": "Shot Blasting & Fettling",
   "scope": "casting",
   "groups": [
    {
     "name": null,
     "steps": [
      {
       "id": "5.1",
       "name": "Shot Blasting",
       "checks": [
        {
         "id": "5.1.1",
         "step": "5.1",
         "sample": "1",
         "param": "Surface finish & casting defect",
         "method": "Visual",
         "criteria": "As per material specification",
         "action": "Re-shot blasting / Salvaging / Reject",
         "actions": [
          "Re-shot blasting",
          "Salvaging",
          "Reject"
         ],
         "tbc": false,
         "kind": "yn"
        }
       ],
       "optional": false,
       "sampled": false
      },
      {
       "id": "5.2",
       "name": "Fettling",
       "checks": [
        {
         "id": "5.2.1",
         "step": "5.2",
         "sample": "1",
         "param": "Critical dimensions",
         "method": "Scale / tape / vernier / gauge",
         "criteria": "As per drawing",
         "action": "Salvaging / Reject",
         "actions": [
          "Salvaging",
          "Reject"
         ],
         "tbc": false,
         "kind": "dim"
        },
        {
         "id": "5.2.2",
         "step": "5.2",
         "sample": "1",
         "param": "D.P. test",
         "method": "DP test kit",
         "criteria": "No surface crack",
         "action": "Salvaging / Reject",
         "actions": [
          "Salvaging",
          "Reject"
         ],
         "tbc": false,
         "kind": "yn"
        }
       ],
       "optional": false,
       "sampled": false
      }
     ]
    }
   ],
   "optional": false
  },
  {
   "no": 6,
   "name": "Heat Treatment",
   "scope": "casting",
   "groups": [
    {
     "name": null,
     "steps": [
      {
       "id": "6.1",
       "name": "Heat Treatment",
       "checks": [
        {
         "id": "6.1.1",
         "step": "6.1",
         "sample": "1",
         "param": "Heat cycle",
         "method": "Thermocouple, indicator, recorder",
         "criteria": "As per method plan Doc No. DCL/MTD/01",
         "action": "Re-heat treatment / Reject",
         "actions": [
          "Re-heat treatment",
          "Reject"
         ],
         "tbc": false,
         "kind": "yn"
        }
       ],
       "optional": false,
       "sampled": false
      }
     ]
    }
   ],
   "optional": false
  },
  {
   "no": 7,
   "name": "Non-Destructive Testing (NDT)",
   "scope": "casting",
   "groups": [
    {
     "name": null,
     "steps": [
      {
       "id": "7.1",
       "name": "D.P. Test",
       "checks": [
        {
         "id": "7.1.1",
         "step": "7.1",
         "sample": "As per PO / QAP requirement",
         "param": "Surface defects",
         "method": "DP testing kit",
         "criteria": "As per IS: or as per PO/QAP",
         "action": "Salvaging / Reject",
         "actions": [
          "Salvaging",
          "Reject"
         ],
         "tbc": false,
         "kind": "yn"
        }
       ],
       "optional": true,
       "sampled": false
      },
      {
       "id": "7.2",
       "name": "Ultrasonic Testing",
       "checks": [
        {
         "id": "7.2.1",
         "step": "7.2",
         "sample": "As per PO / QAP requirement",
         "param": "Internal flaw of casting",
         "method": "Ultrasonic testing machine",
         "criteria": "As per IS: or as per PO/QAP",
         "action": "Rejected & remelted",
         "actions": [
          "Rejected & remelted"
         ],
         "tbc": false,
         "kind": "yn"
        }
       ],
       "optional": true,
       "sampled": false
      },
      {
       "id": "7.3",
       "name": "Radiography",
       "checks": [
        {
         "id": "7.3.1",
         "step": "7.3",
         "sample": "As per PO / QAP requirement",
         "param": "Internal flaw of casting",
         "method": "Radiography camera",
         "criteria": "As per ASTM E466 Level II or as per PO/QAP",
         "action": "Rejected & remelted",
         "actions": [
          "Rejected & remelted"
         ],
         "tbc": false,
         "kind": "yn"
        }
       ],
       "optional": true,
       "sampled": false
      },
      {
       "id": "7.4",
       "name": "Magnetic Particle Test",
       "checks": [
        {
         "id": "7.4.1",
         "step": "7.4",
         "sample": "100% where applicable",
         "param": "Sub-surface crack",
         "method": "MPI tester",
         "criteria": "To be confirmed",
         "action": "To be confirmed",
         "actions": [
          "Salvaging",
          "Reject"
         ],
         "tbc": true,
         "kind": "yn",
         "assumed": true
        }
       ],
       "optional": true,
       "sampled": false
      }
     ]
    }
   ],
   "optional": true
  },
  {
   "no": 8,
   "name": "Mechanical & Metallurgical Testing",
   "scope": "heat",
   "groups": [
    {
     "name": null,
     "steps": [
      {
       "id": "8.1",
       "name": "Tensile Test",
       "checks": [
        {
         "id": "8.1.1",
         "step": "8.1",
         "sample": "One sample per heat",
         "param": "UTS, YS, E%, RA%, Impact",
         "method": "Universal testing machine, impact tester, vernier caliper, micrometer",
         "criteria": "As per ASTM A370 MT:CBC:001",
         "action": "Rejected & returned to re-heat treatment",
         "actions": [
          "Rejected & returned to re-heat treatment"
         ],
         "tbc": false,
         "kind": "mech"
        }
       ],
       "optional": true,
       "sampled": false
      },
      {
       "id": "8.2",
       "name": "Microstructure",
       "checks": [
        {
         "id": "8.2.1",
         "step": "8.2",
         "sample": "One sample per heat",
         "param": "Microstructure & hardness of test lug",
         "method": "Microscope",
         "criteria": "As per IS: or as per customer specification/QAP",
         "action": "Rejected & returned to re-heat treatment",
         "actions": [
          "Rejected & returned to re-heat treatment"
         ],
         "tbc": false,
         "kind": "yn"
        }
       ],
       "optional": true,
       "sampled": false
      },
      {
       "id": "8.3",
       "name": "Hardness",
       "checks": [
        {
         "id": "8.3.1",
         "step": "8.3",
         "sample": "10% per heat / as per customer requirement",
         "param": "Hardness",
         "method": "Hardness testing machine",
         "criteria": "As per drawing / standard specification",
         "action": "Rejected & returned to re-heat treatment",
         "actions": [
          "Rejected & returned to re-heat treatment"
         ],
         "tbc": false,
         "kind": "spec",
         "unit": "HBW"
        }
       ],
       "optional": true,
       "sampled": true
      },
      {
       "id": "8.4",
       "name": "Impact Test",
       "checks": [
        {
         "id": "8.4.1",
         "step": "8.4",
         "sample": "As per customer's QAP",
         "param": "Impact strength",
         "method": "Impact tester",
         "criteria": "Charpy V-notch Type A as per ASTM A370",
         "action": "Re-heat treatment",
         "actions": [
          "Re-heat treatment"
         ],
         "tbc": false,
         "kind": "spec",
         "unit": "J"
        }
       ],
       "optional": true,
       "sampled": false
      }
     ]
    }
   ],
   "optional": true
  },
  {
   "no": 9,
   "name": "Machining (if applicable)",
   "scope": "casting",
   "groups": [
    {
     "name": null,
     "steps": [
      {
       "id": "9.1",
       "name": "After Machining",
       "checks": [
        {
         "id": "9.1.1",
         "step": "9.1",
         "sample": "1",
         "param": "Machined dimensions",
         "method": "Scale / vernier / micrometer",
         "criteria": "To be confirmed",
         "action": "Re-machined / Reject",
         "actions": [
          "Re-machined",
          "Reject"
         ],
         "tbc": true,
         "kind": "dim"
        }
       ],
       "optional": true,
       "sampled": false
      }
     ]
    }
   ],
   "optional": true
  },
  {
   "no": 10,
   "name": "Final Inspection & Packing",
   "scope": "casting",
   "groups": [
    {
     "name": null,
     "steps": [
      {
       "id": "10.1",
       "name": "Final Inspection",
       "checks": [
        {
         "id": "10.1.1",
         "step": "10.1",
         "sample": "1",
         "param": "Visual inspection",
         "method": "Visual",
         "criteria": "As per drawing",
         "action": "Rejected & returned for melting",
         "actions": [
          "Rejected & returned for melting"
         ],
         "tbc": false,
         "kind": "yn"
        },
        {
         "id": "10.1.2",
         "step": "10.1",
         "sample": "1",
         "param": "Specified dimensions as per drawing & spec.",
         "method": "Inspection gauge, measuring instruments",
         "criteria": "As per drawing",
         "action": "Rejected & returned for melting",
         "actions": [
          "Rejected & returned for melting"
         ],
         "tbc": false,
         "kind": "dim"
        }
       ],
       "optional": false,
       "sampled": false
      },
      {
       "id": "10.2",
       "name": "Packing",
       "checks": [
        {
         "id": "10.2.1",
         "step": "10.2",
         "sample": "1",
         "param": "1 pc in each bag / wooden box (heat wise)",
         "method": "Poly bag / wooden box",
         "criteria": "As per specification / PO",
         "action": "Re-packing",
         "actions": [
          "Re-packing"
         ],
         "tbc": false,
         "kind": "yn"
        }
       ],
       "optional": false,
       "sampled": false
      }
     ]
    }
   ],
   "optional": false
  }
 ]
};
